"""capitalized the types

Revision ID: 022387bfb2c2
Revises: d86a3a39e0ee
Create Date: 2026-05-01 12:20:30.188591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '022387bfb2c2'
down_revision: Union[str, Sequence[str], None] = 'd86a3a39e0ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision', sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column(
        'decision',
        sa.Column('is_executed', sa.Boolean(), nullable=True)
    )

    # Step 2: fill existing rows
    op.execute("""
        UPDATE decision
        SET is_executed = false
    """)

    # Step 3: enforce NOT NULL
    op.alter_column(
        'decision',
        'is_executed',
        nullable=False
    )



