"""payment_method is nullable

Revision ID: a9d4f993dd6f
Revises: 22608038f779
Create Date: 2026-04-30 15:05:44.391224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9d4f993dd6f'
down_revision: Union[str, Sequence[str], None] = '22608038f779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderstate', sa.Column('payment_method', sa.Enum('cod', 'prepaid', name='payment_typeenum'), nullable=True))
    op.drop_column('orderstate', 'payment_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderstate', sa.Column('payment_type', postgresql.ENUM('cod', 'prepaid', name='payment_typeenum'), autoincrement=False, nullable=False))
    op.drop_column('orderstate', 'payment_method')
    # ### end Alembic commands ###
