"""decision mismatch fixed

Revision ID: d86a3a39e0ee
Revises: 296c4439ddf3
Create Date: 2026-05-01 11:30:06.323136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd86a3a39e0ee'
down_revision: Union[str, Sequence[str], None] = '296c4439ddf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decision', 'decison_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision', sa.Column('decison_status', postgresql.ENUM('released', 'on_hold', 'partially_released', 'manual_check', 'block', 'cancelled', 'recovery', name='statusenum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
